apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis-app
spec:
  containers:
    - name: redis-container
      image: redis123
      ports:
        - containerPort: 8080
      resources:
        requests:
          memory: "1Gi"
          cpu: 1
        limits:
          memory: "2Gi"
          cpu: 2