apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: LoadBalancer
  ports:
    - targetport: 80
      port: 80
      nodePort: 3008
  selector:
    app: myapp
    type: front-end