apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis-app
spec:
  containers:
    - name: redis-container
      image: redis123
  tolerations:
    - key: "app"
      operator: "Equal"
      value: "blue"
      effect: "NoSchedule"
# or
  tolerations:
    - key: "app"
      operator: "Exists"
      effect: "NoSchedule"